from enum import Enum


class CoreMetadataGenerationModeType0(str, Enum):
    ANIMA_IMG2IMG = "anima_img2img"
    ANIMA_INPAINT = "anima_inpaint"
    ANIMA_OUTPAINT = "anima_outpaint"
    ANIMA_TXT2IMG = "anima_txt2img"
    COGVIEW4_IMG2IMG = "cogview4_img2img"
    COGVIEW4_INPAINT = "cogview4_inpaint"
    COGVIEW4_OUTPAINT = "cogview4_outpaint"
    COGVIEW4_TXT2IMG = "cogview4_txt2img"
    FLUX2_IMG2IMG = "flux2_img2img"
    FLUX2_INPAINT = "flux2_inpaint"
    FLUX2_OUTPAINT = "flux2_outpaint"
    FLUX2_TXT2IMG = "flux2_txt2img"
    FLUX_IMG2IMG = "flux_img2img"
    FLUX_INPAINT = "flux_inpaint"
    FLUX_OUTPAINT = "flux_outpaint"
    FLUX_TXT2IMG = "flux_txt2img"
    IMG2IMG = "img2img"
    INPAINT = "inpaint"
    OUTPAINT = "outpaint"
    QWEN_IMAGE_IMG2IMG = "qwen_image_img2img"
    QWEN_IMAGE_INPAINT = "qwen_image_inpaint"
    QWEN_IMAGE_OUTPAINT = "qwen_image_outpaint"
    QWEN_IMAGE_TXT2IMG = "qwen_image_txt2img"
    SD3_IMG2IMG = "sd3_img2img"
    SD3_INPAINT = "sd3_inpaint"
    SD3_OUTPAINT = "sd3_outpaint"
    SD3_TXT2IMG = "sd3_txt2img"
    SDXL_IMG2IMG = "sdxl_img2img"
    SDXL_INPAINT = "sdxl_inpaint"
    SDXL_OUTPAINT = "sdxl_outpaint"
    SDXL_TXT2IMG = "sdxl_txt2img"
    TXT2IMG = "txt2img"
    Z_IMAGE_IMG2IMG = "z_image_img2img"
    Z_IMAGE_INPAINT = "z_image_inpaint"
    Z_IMAGE_OUTPAINT = "z_image_outpaint"
    Z_IMAGE_TXT2IMG = "z_image_txt2img"

    def __str__(self) -> str:
        return str(self.value)
